CC=gcc -std=c99
int: 
	$(CC) allocate.c calculations.c checks.c logic_double.c logic_int.c main.c -lm
double: 
	$(CC) allocate.c calculations.c checks.c logic_double.c logic_int.c main.c -D USE_DBL -lm